language: go
go:
- 1.9
script: go test -v ./...
after_success:
- bin/build_all
- docker build -t orangeopensource/prometheus-fast-remote .
- if [ "x$TRAVIS_TAG" != "x" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker build -t orangeopensource/prometheus-fast-remote:$( echo "$TRAVIS_TAG" |
  cut -c 2- ) .; fi
- if [ "x$TRAVIS_TAG" != "x" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push orangeopensource/prometheus-fast-remote:$( echo "$TRAVIS_TAG" | cut
  -c 2- ); fi
- if [ "x$TRAVIS_TAG" != "x" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push orangeopensource/prometheus-fast-remote; fi
deploy:
  provider: releases
  api_key:
    secure: NQ0TrnXUpGanSZ+sVVqjXLRM4JMhVrYxMB3tgnQdJXE68eekClAPYhQH03+OXNzvzmzJP0p5kxRElcjW3dpJFml/LCaP9xCWrzqZLjJRaeIo804UzZkJ5kYDEHGPtpPJ6k0gyNK5TyUDtCmUPYEpTbE/x77y7UoICZ/nRdiUiEQoxUlrYMSV5rF5UmtUd0gcIWPvuPGaxMjQ+FofSuffIDItLQgsmXfNPhyyEHD56keWL5zf36Ta4p9lBRs4jf2m+4j2lx12gIqqlOElcJDOJI861T2x4lplAGO7c46NU6F0mnsOfBFuTfFa7tfN68Z6i2A1UtKU18qsQw1ZrqlKo/9QILWNXIn9NrWYnYgIVEqJJMYaw4/r+VEXA83JudNC90BjDHN4g6LhLrYFkEbOsjWVqlGF4SptzuS4cCEIyUUdDr5wzQIVL4aAGnlPsDTjtF+pEig6ox9+GEZ/y2+wiNArsq4d2Ka3QAv6aoj5bdqvgxsQcLNNYCgKDZpHkMIbf8cVTg5XxTmgXfZ/ziV8siWjjsUpzg2sVaMG+eAYJhlXFI0t7qR0x48bQuSyQwvwUWrteyeEU+9rx5UgZJ+0Djh1CxS1pwy2bmrJgueeG3kgTnmnAtRqesU5OPn4li00QzLfUFH7tPYEOdHW39UapC4RaUI1kBpBIcoVtyeiXlI=
  file:
  - out/adapter_darwin_amd64
  - out/adapter_linux_386
  - out/adapter_linux_amd64
  - out/adapter_windows_386.exe
  - out/adapter_windows_amd64.exe
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: mzV6n5vju7/zRPP3lXurgXpJ8baT2NV329O+jnZbfFJNIEgI7oT+98EqpN/0hqKHF+lXfUrPKwFmIK0Blz2/7CsYtpFXKDYYot63Fmfz3nardewnOhpbrjW7qtyPVpeRn1fpJrYHlT6BiJ74RXQTkPllLUmPuTiv0+Gi5TbjlP4snRCT5/QW9KW7pGvSkFSmXhyOU0njQTX4k0AB6GVljiRZojk2z99FO6n2cZ6n/bTlRsj7psWD3m8EKgA68BFb2mFUwggz7aZAjtvUtoQ+KF+EiBGG3CxlVREyYpw5+fZGYS+V3Iw2ZYTJ+xXYe9/TbXRfMBFLIvg2DJD0zqVBqU2TTvK3oLxKwcspN3wA9i1ynYJkUwjq9onvwk7pgzsNulXRdBJrMtxy3lnzLKpYvEA2e5gLpuUqkTqYmop9eZweqY9Qn9oy63pa8M/GB+OZw4S3PTlMTIWkj9YU4GmZt3U+qztzrYjvbws7/2eucik4NIDiaAXPOJVASoLgEeZxJgtOGn1fTFL+xkPv4vQft2U6rYivAokMs5adNyVd0PNqKKoA9c//RMAiww8dWscGN0lNDwYQ7ju2VeDOYa4/JQEIsm1udeRcyD2pIpXl24gsS1nRSL4sEN17pSmauDlQIfgAKntV3cbKqYY41F6OxvN2MvC/S5DTA8TL/oGTqUo=
  - secure: H6h7w5uJzOW9k3j679D0EPpumd7vgj1nUZXb+9twhaAy10GuM2uBx8JAnD7nA0MexlIsDZhOUAehW8kI/r8JFly+wNgFHZtWIf+rNLGSFmJrNLULPgnO2AUdQTvYFwsj52z838J8315/KjfZPpWVaYppfKmI9SB18twYgOsMg9S5QO3qcV8AjP1C9YhjiObexR81gDo2/wI8HoC//Ae7Qr0geiHHoRPCfp2/bJ0MhQ9QIfpsm8BB3DpnUR+qTy7UmA3d0SDzfSEBdTN5buYD3rLFDZiCyY03cgODTWrV8ByBWhIfTCuDjzRxl2cZpUxHBKm8RrJtc0Zk+2K6X8/q9N9HfAvwI6ZMRJZozwNj+n9l3QB14c8quJKwe8vkvfPjM4KKqu1XPEVhOqCfG+a8IrNUiIgfmHpa3rfMNSifDYqmbYQuTuQVTbvpXcJk58xVc0H2oX+7w+1diLpZ5TvoxZeaNWcQMDySqcEzGlTdrGFN2BTUAPrdRD7rJMOQEfXLlxFAW6eYvEclayFJUgTBPFcC+AIMktx8DlrXrVZb3Fb/fokrEwSXGOhLWZEDaHrk3nCJ0Pnfv3VtuNXEkBEpvnkLHZ7k4XGf1cCZ8IkUz4a4eGWA5kYeZT+VDkhtbtFtUledpo4Mpw2B6H7h3dFx11KLbk3Q2RVXTI9jUE/t/Es=
